export const API_URL = 'https://api.unsplash.com';
export const API_URL_AUTH = 'https://unsplash.com/oauth/authorize';
export const API_URL_PHOTOS = `${API_URL}/photos`;
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token';
export const ACCESS_KEY = 'Wy9NkfWgA3qspHOf19EXfoT-CrDxYN7dgflpLY8i6IE';
export const SECRET_KEY = 'dB89Idl_s8XuvxV-RDYi1xaKXILlbeyIEzVIDCmOnjY';
export const REDIRECT_URI = 'http://localhost:5173/';
export const RESPONSE_TYPE = 'code';
export const SCOPE = 'public read_user read_photos write_likes';
